// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import { EntityTypeComponent } from './entity-type-component.js';
import { HealthComponent } from './health-component.js';
import { Mass } from './mass.js';
import { PerceptionComponent } from './perception-component.js';
import { Position } from './position.js';
import { Velocity } from './velocity.js';


export enum Component {
  NONE = 0,
  EntityTypeComponent = 1,
  HealthComponent = 2,
  Mass = 3,
  Position = 4,
  Velocity = 5,
  PerceptionComponent = 6
}

export function unionToComponent(
  type: Component,
  accessor: (obj:EntityTypeComponent|HealthComponent|Mass|PerceptionComponent|Position|Velocity) => EntityTypeComponent|HealthComponent|Mass|PerceptionComponent|Position|Velocity|null
): EntityTypeComponent|HealthComponent|Mass|PerceptionComponent|Position|Velocity|null {
  switch(Component[type]) {
    case 'NONE': return null; 
    case 'EntityTypeComponent': return accessor(new EntityTypeComponent())! as EntityTypeComponent;
    case 'HealthComponent': return accessor(new HealthComponent())! as HealthComponent;
    case 'Mass': return accessor(new Mass())! as Mass;
    case 'Position': return accessor(new Position())! as Position;
    case 'Velocity': return accessor(new Velocity())! as Velocity;
    case 'PerceptionComponent': return accessor(new PerceptionComponent())! as PerceptionComponent;
    default: return null;
  }
}

export function unionListToComponent(
  type: Component, 
  accessor: (index: number, obj:EntityTypeComponent|HealthComponent|Mass|PerceptionComponent|Position|Velocity) => EntityTypeComponent|HealthComponent|Mass|PerceptionComponent|Position|Velocity|null, 
  index: number
): EntityTypeComponent|HealthComponent|Mass|PerceptionComponent|Position|Velocity|null {
  switch(Component[type]) {
    case 'NONE': return null; 
    case 'EntityTypeComponent': return accessor(index, new EntityTypeComponent())! as EntityTypeComponent;
    case 'HealthComponent': return accessor(index, new HealthComponent())! as HealthComponent;
    case 'Mass': return accessor(index, new Mass())! as Mass;
    case 'Position': return accessor(index, new Position())! as Position;
    case 'Velocity': return accessor(index, new Velocity())! as Velocity;
    case 'PerceptionComponent': return accessor(index, new PerceptionComponent())! as PerceptionComponent;
    default: return null;
  }
}
