// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum DirectionEnum {
  UP = 0,
  DOWN = 1,
  LEFT = 2,
  RIGHT = 3,
  FORWARD = 4,
  BACKWARD = 5
}
