// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { EntityInterface } from './entity-interface.js';
import { QueryResponse } from './query-response.js';
import { WorldView } from './world-view.js';


export class PerceptionResponse {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):PerceptionResponse {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsPerceptionResponse(bb:flatbuffers.ByteBuffer, obj?:PerceptionResponse):PerceptionResponse {
  return (obj || new PerceptionResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsPerceptionResponse(bb:flatbuffers.ByteBuffer, obj?:PerceptionResponse):PerceptionResponse {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new PerceptionResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

entity(obj?:EntityInterface):EntityInterface|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new EntityInterface()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

worldView(obj?:WorldView):WorldView|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new WorldView()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

gameClockTicks():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

itemsEntities(index: number, obj?:EntityInterface):EntityInterface|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? (obj || new EntityInterface()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

itemsEntitiesLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

queryResponses(index: number, obj?:QueryResponse):QueryResponse|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? (obj || new QueryResponse()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

queryResponsesLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startPerceptionResponse(builder:flatbuffers.Builder) {
  builder.startObject(5);
}

static addEntity(builder:flatbuffers.Builder, entityOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, entityOffset, 0);
}

static addWorldView(builder:flatbuffers.Builder, worldViewOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, worldViewOffset, 0);
}

static addGameClockTicks(builder:flatbuffers.Builder, gameClockTicks:bigint) {
  builder.addFieldInt64(2, gameClockTicks, BigInt('0'));
}

static addItemsEntities(builder:flatbuffers.Builder, itemsEntitiesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, itemsEntitiesOffset, 0);
}

static createItemsEntitiesVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startItemsEntitiesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addQueryResponses(builder:flatbuffers.Builder, queryResponsesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, queryResponsesOffset, 0);
}

static createQueryResponsesVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startQueryResponsesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endPerceptionResponse(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static finishPerceptionResponseBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset);
}

static finishSizePrefixedPerceptionResponseBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, undefined, true);
}

}
