// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



export class VoxelGridView {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):VoxelGridView {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsVoxelGridView(bb:flatbuffers.ByteBuffer, obj?:VoxelGridView):VoxelGridView {
  return (obj || new VoxelGridView()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsVoxelGridView(bb:flatbuffers.ByteBuffer, obj?:VoxelGridView):VoxelGridView {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new VoxelGridView()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

width():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

height():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

depth():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

xOffset():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

yOffset():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

zOffset():number {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

terrainData(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.readInt32(this.bb!.__vector(this.bb_pos + offset) + index * 4) : 0;
}

terrainDataLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

terrainDataArray():Int32Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? new Int32Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

entityData(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.readInt32(this.bb!.__vector(this.bb_pos + offset) + index * 4) : 0;
}

entityDataLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

entityDataArray():Int32Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? new Int32Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

static startVoxelGridView(builder:flatbuffers.Builder) {
  builder.startObject(8);
}

static addWidth(builder:flatbuffers.Builder, width:number) {
  builder.addFieldInt32(0, width, 0);
}

static addHeight(builder:flatbuffers.Builder, height:number) {
  builder.addFieldInt32(1, height, 0);
}

static addDepth(builder:flatbuffers.Builder, depth:number) {
  builder.addFieldInt32(2, depth, 0);
}

static addXOffset(builder:flatbuffers.Builder, xOffset:number) {
  builder.addFieldInt32(3, xOffset, 0);
}

static addYOffset(builder:flatbuffers.Builder, yOffset:number) {
  builder.addFieldInt32(4, yOffset, 0);
}

static addZOffset(builder:flatbuffers.Builder, zOffset:number) {
  builder.addFieldInt32(5, zOffset, 0);
}

static addTerrainData(builder:flatbuffers.Builder, terrainDataOffset:flatbuffers.Offset) {
  builder.addFieldOffset(6, terrainDataOffset, 0);
}

static createTerrainDataVector(builder:flatbuffers.Builder, data:number[]|Int32Array):flatbuffers.Offset;
/**
 * @deprecated This Uint8Array overload will be removed in the future.
 */
static createTerrainDataVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset;
static createTerrainDataVector(builder:flatbuffers.Builder, data:number[]|Int32Array|Uint8Array):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt32(data[i]!);
  }
  return builder.endVector();
}

static startTerrainDataVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addEntityData(builder:flatbuffers.Builder, entityDataOffset:flatbuffers.Offset) {
  builder.addFieldOffset(7, entityDataOffset, 0);
}

static createEntityDataVector(builder:flatbuffers.Builder, data:number[]|Int32Array):flatbuffers.Offset;
/**
 * @deprecated This Uint8Array overload will be removed in the future.
 */
static createEntityDataVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset;
static createEntityDataVector(builder:flatbuffers.Builder, data:number[]|Int32Array|Uint8Array):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt32(data[i]!);
  }
  return builder.endVector();
}

static startEntityDataVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endVoxelGridView(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static finishVoxelGridViewBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset);
}

static finishSizePrefixedVoxelGridViewBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, undefined, true);
}

static createVoxelGridView(builder:flatbuffers.Builder, width:number, height:number, depth:number, xOffset:number, yOffset:number, zOffset:number, terrainDataOffset:flatbuffers.Offset, entityDataOffset:flatbuffers.Offset):flatbuffers.Offset {
  VoxelGridView.startVoxelGridView(builder);
  VoxelGridView.addWidth(builder, width);
  VoxelGridView.addHeight(builder, height);
  VoxelGridView.addDepth(builder, depth);
  VoxelGridView.addXOffset(builder, xOffset);
  VoxelGridView.addYOffset(builder, yOffset);
  VoxelGridView.addZOffset(builder, zOffset);
  VoxelGridView.addTerrainData(builder, terrainDataOffset);
  VoxelGridView.addEntityData(builder, entityDataOffset);
  return VoxelGridView.endVoxelGridView(builder);
}
}
