from typing import Protocol


class AudioManagerProtocol(Protocol):
    """Protocol describing the public surface of an audio manager used by the engine.

    This mirrors the primary methods provided by `MusicAndAmbienceManager` so
    other engine components can accept a typed audio manager without depending
    on the concrete implementation.
    """

    def load_music(self, file_path: str | bytes) -> None: ...
    def play_music(self, loops: int = -1) -> None: ...
    def pause_music(self) -> None: ...
    def resume_music(self) -> None: ...
    def stop_music(self) -> None: ...
    def fade_in_music(self, loops: int = -1, fade_ms: int = 1000) -> None: ...
    def fade_out_music(self, fade_ms: int = 1000) -> None: ...
    def set_music_volume(self, volume: int) -> None: ...
    def get_music_volume(self) -> int: ...
    def is_music_playing(self) -> bool: ...
    def is_music_paused(self) -> bool: ...

    def load_ambient(self, name: str, file_path: str | bytes) -> None: ...
    def play_ambient(self, name: str, loops: int = -1, volume: int = 128) -> int: ...
    def stop_ambient(self, name: str) -> None: ...
    def stop_all_ambient(self) -> None: ...
    def fade_ambient(self, name: str, fade_ms: int) -> None: ...
    def set_ambient_volume(self, volume: int) -> None: ...

    def cleanup(self) -> None: ...
