// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class EntityInterface {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):EntityInterface {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsEntityInterface(bb:flatbuffers.ByteBuffer, obj?:EntityInterface):EntityInterface {
  return (obj || new EntityInterface()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsEntityInterface(bb:flatbuffers.ByteBuffer, obj?:EntityInterface):EntityInterface {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new EntityInterface()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

entityId():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

entityData(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index) : 0;
}

entityDataLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

entityDataArray():Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

static startEntityInterface(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addEntityId(builder:flatbuffers.Builder, entityId:number) {
  builder.addFieldInt32(0, entityId, 0);
}

static addEntityData(builder:flatbuffers.Builder, entityDataOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, entityDataOffset, 0);
}

static createEntityDataVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]!);
  }
  return builder.endVector();
}

static startEntityDataVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
}

static endEntityInterface(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createEntityInterface(builder:flatbuffers.Builder, entityId:number, entityDataOffset:flatbuffers.Offset):flatbuffers.Offset {
  EntityInterface.startEntityInterface(builder);
  EntityInterface.addEntityId(builder, entityId);
  EntityInterface.addEntityData(builder, entityDataOffset);
  return EntityInterface.endEntityInterface(builder);
}
}
