// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class EntityTypeComponent {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):EntityTypeComponent {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsEntityTypeComponent(bb:flatbuffers.ByteBuffer, obj?:EntityTypeComponent):EntityTypeComponent {
  return (obj || new EntityTypeComponent()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsEntityTypeComponent(bb:flatbuffers.ByteBuffer, obj?:EntityTypeComponent):EntityTypeComponent {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new EntityTypeComponent()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

type():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

subType0():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

subType1():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

static startEntityTypeComponent(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addType(builder:flatbuffers.Builder, type:number) {
  builder.addFieldInt32(0, type, 0);
}

static addSubType0(builder:flatbuffers.Builder, subType0:number) {
  builder.addFieldInt32(1, subType0, 0);
}

static addSubType1(builder:flatbuffers.Builder, subType1:number) {
  builder.addFieldInt32(2, subType1, 0);
}

static endEntityTypeComponent(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createEntityTypeComponent(builder:flatbuffers.Builder, type:number, subType0:number, subType1:number):flatbuffers.Offset {
  EntityTypeComponent.startEntityTypeComponent(builder);
  EntityTypeComponent.addType(builder, type);
  EntityTypeComponent.addSubType0(builder, subType0);
  EntityTypeComponent.addSubType1(builder, subType1);
  return EntityTypeComponent.endEntityTypeComponent(builder);
}
}
