// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class GridData {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):GridData {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsGridData(bb:flatbuffers.ByteBuffer, obj?:GridData):GridData {
  return (obj || new GridData()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsGridData(bb:flatbuffers.ByteBuffer, obj?:GridData):GridData {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new GridData()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

terrainId():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

entityId():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

eventId():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

lightingLevel():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

static startGridData(builder:flatbuffers.Builder) {
  builder.startObject(4);
}

static addTerrainId(builder:flatbuffers.Builder, terrainId:number) {
  builder.addFieldInt32(0, terrainId, 0);
}

static addEntityId(builder:flatbuffers.Builder, entityId:number) {
  builder.addFieldInt32(1, entityId, 0);
}

static addEventId(builder:flatbuffers.Builder, eventId:number) {
  builder.addFieldInt32(2, eventId, 0);
}

static addLightingLevel(builder:flatbuffers.Builder, lightingLevel:number) {
  builder.addFieldFloat32(3, lightingLevel, 0.0);
}

static endGridData(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createGridData(builder:flatbuffers.Builder, terrainId:number, entityId:number, eventId:number, lightingLevel:number):flatbuffers.Offset {
  GridData.startGridData(builder);
  GridData.addTerrainId(builder, terrainId);
  GridData.addEntityId(builder, entityId);
  GridData.addEventId(builder, eventId);
  GridData.addLightingLevel(builder, lightingLevel);
  return GridData.endGridData(builder);
}
}
