// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class HealthComponent {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):HealthComponent {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsHealthComponent(bb:flatbuffers.ByteBuffer, obj?:HealthComponent):HealthComponent {
  return (obj || new HealthComponent()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsHealthComponent(bb:flatbuffers.ByteBuffer, obj?:HealthComponent):HealthComponent {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new HealthComponent()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

healthLevel():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

maxHealth():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

static startHealthComponent(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addHealthLevel(builder:flatbuffers.Builder, healthLevel:number) {
  builder.addFieldFloat32(0, healthLevel, 0.0);
}

static addMaxHealth(builder:flatbuffers.Builder, maxHealth:number) {
  builder.addFieldFloat32(1, maxHealth, 0.0);
}

static endHealthComponent(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createHealthComponent(builder:flatbuffers.Builder, healthLevel:number, maxHealth:number):flatbuffers.Offset {
  HealthComponent.startHealthComponent(builder);
  HealthComponent.addHealthLevel(builder, healthLevel);
  HealthComponent.addMaxHealth(builder, maxHealth);
  return HealthComponent.endHealthComponent(builder);
}
}
