// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class Mass {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Mass {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsMass(bb:flatbuffers.ByteBuffer, obj?:Mass):Mass {
  return (obj || new Mass()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsMass(bb:flatbuffers.ByteBuffer, obj?:Mass):Mass {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Mass()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

mass():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

static startMass(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addMass(builder:flatbuffers.Builder, mass:number) {
  builder.addFieldFloat32(0, mass, 0.0);
}

static endMass(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createMass(builder:flatbuffers.Builder, mass:number):flatbuffers.Offset {
  Mass.startMass(builder);
  Mass.addMass(builder, mass);
  return Mass.endMass(builder);
}
}
