// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class PerceptionComponent {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):PerceptionComponent {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsPerceptionComponent(bb:flatbuffers.ByteBuffer, obj?:PerceptionComponent):PerceptionComponent {
  return (obj || new PerceptionComponent()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsPerceptionComponent(bb:flatbuffers.ByteBuffer, obj?:PerceptionComponent):PerceptionComponent {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new PerceptionComponent()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

perceptionArea():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

zPerceptionArea():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

static startPerceptionComponent(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addPerceptionArea(builder:flatbuffers.Builder, perceptionArea:number) {
  builder.addFieldInt32(0, perceptionArea, 0);
}

static addZPerceptionArea(builder:flatbuffers.Builder, zPerceptionArea:number) {
  builder.addFieldInt32(1, zPerceptionArea, 0);
}

static endPerceptionComponent(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createPerceptionComponent(builder:flatbuffers.Builder, perceptionArea:number, zPerceptionArea:number):flatbuffers.Offset {
  PerceptionComponent.startPerceptionComponent(builder);
  PerceptionComponent.addPerceptionArea(builder, perceptionArea);
  PerceptionComponent.addZPerceptionArea(builder, zPerceptionArea);
  return PerceptionComponent.endPerceptionComponent(builder);
}
}
