// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class QueryResponse {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):QueryResponse {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsQueryResponse(bb:flatbuffers.ByteBuffer, obj?:QueryResponse):QueryResponse {
  return (obj || new QueryResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsQueryResponse(bb:flatbuffers.ByteBuffer, obj?:QueryResponse):QueryResponse {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new QueryResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

queryId():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

queryData(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index) : 0;
}

queryDataLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

queryDataArray():Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

static startQueryResponse(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addQueryId(builder:flatbuffers.Builder, queryId:number) {
  builder.addFieldInt32(0, queryId, 0);
}

static addQueryData(builder:flatbuffers.Builder, queryDataOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, queryDataOffset, 0);
}

static createQueryDataVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]!);
  }
  return builder.endVector();
}

static startQueryDataVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
}

static endQueryResponse(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createQueryResponse(builder:flatbuffers.Builder, queryId:number, queryDataOffset:flatbuffers.Offset):flatbuffers.Offset {
  QueryResponse.startQueryResponse(builder);
  QueryResponse.addQueryId(builder, queryId);
  QueryResponse.addQueryData(builder, queryDataOffset);
  return QueryResponse.endQueryResponse(builder);
}
}
