// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class Velocity {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Velocity {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsVelocity(bb:flatbuffers.ByteBuffer, obj?:Velocity):Velocity {
  return (obj || new Velocity()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsVelocity(bb:flatbuffers.ByteBuffer, obj?:Velocity):Velocity {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Velocity()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

vx():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

vy():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

vz():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

maxSpeed():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

static startVelocity(builder:flatbuffers.Builder) {
  builder.startObject(4);
}

static addVx(builder:flatbuffers.Builder, vx:number) {
  builder.addFieldFloat32(0, vx, 0.0);
}

static addVy(builder:flatbuffers.Builder, vy:number) {
  builder.addFieldFloat32(1, vy, 0.0);
}

static addVz(builder:flatbuffers.Builder, vz:number) {
  builder.addFieldFloat32(2, vz, 0.0);
}

static addMaxSpeed(builder:flatbuffers.Builder, maxSpeed:number) {
  builder.addFieldFloat32(3, maxSpeed, 0.0);
}

static endVelocity(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createVelocity(builder:flatbuffers.Builder, vx:number, vy:number, vz:number, maxSpeed:number):flatbuffers.Offset {
  Velocity.startVelocity(builder);
  Velocity.addVx(builder, vx);
  Velocity.addVy(builder, vy);
  Velocity.addVz(builder, vz);
  Velocity.addMaxSpeed(builder, maxSpeed);
  return Velocity.endVelocity(builder);
}
}
