// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { EntityInterface } from './entity-interface.js';
import { VoxelGridView } from './voxel-grid-view.js';


export class WorldView {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):WorldView {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsWorldView(bb:flatbuffers.ByteBuffer, obj?:WorldView):WorldView {
  return (obj || new WorldView()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsWorldView(bb:flatbuffers.ByteBuffer, obj?:WorldView):WorldView {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new WorldView()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

width():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

height():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

depth():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

voxelGrid(obj?:VoxelGridView):VoxelGridView|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? (obj || new VoxelGridView()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

entities(index: number, obj?:EntityInterface):EntityInterface|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? (obj || new EntityInterface()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

entitiesLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startWorldView(builder:flatbuffers.Builder) {
  builder.startObject(5);
}

static addWidth(builder:flatbuffers.Builder, width:number) {
  builder.addFieldInt32(0, width, 0);
}

static addHeight(builder:flatbuffers.Builder, height:number) {
  builder.addFieldInt32(1, height, 0);
}

static addDepth(builder:flatbuffers.Builder, depth:number) {
  builder.addFieldInt32(2, depth, 0);
}

static addVoxelGrid(builder:flatbuffers.Builder, voxelGridOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, voxelGridOffset, 0);
}

static addEntities(builder:flatbuffers.Builder, entitiesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, entitiesOffset, 0);
}

static createEntitiesVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startEntitiesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endWorldView(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static finishWorldViewBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset);
}

static finishSizePrefixedWorldViewBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, undefined, true);
}

}
