from enum import StrEnum


class InputEventActionType(StrEnum):
    WALK_LEFT = "WALK_LEFT"
    WALK_RIGHT = "WALK_RIGHT"
    WALK_UP = "WALK_UP"
    WALK_DOWN = "WALK_DOWN"

    WALK_LEFT_UP = "WALK_LEFT_UP"
    WALK_LEFT_DOWN = "WALK_LEFT_DOWN"
    WALK_RIGHT_UP = "WALK_RIGHT_UP"
    WALK_RIGHT_DOWN = "WALK_RIGHT_DOWN"

    WALK_LEFT_JUMP = "WALK_LEFT_JUMP"
    WALK_RIGHT_JUMP = "WALK_RIGHT_JUMP"
    WALK_UP_JUMP = "WALK_UP_JUMP"
    WALK_DOWN_JUMP = "WALK_DOWN_JUMP"

    JUMP = "JUMP"
    TAKE_ITEM = "TAKE_ITEM"
    USE_ITEM_0 = "USE_ITEM_0"
    USE_ITEM_1 = "USE_ITEM_1"
    USE_ITEM_2 = "USE_ITEM_2"
    USE_ITEM_3 = "USE_ITEM_3"
    USE_ITEM_4 = "USE_ITEM_4"
    USE_ITEM_5 = "USE_ITEM_5"
    USE_ITEM_6 = "USE_ITEM_6"
    USE_ITEM_7 = "USE_ITEM_7"
    USE_ITEM_8 = "USE_ITEM_8"
    USE_ITEM_9 = "USE_ITEM_9"

    MOUSE_LEFT_BUTTON_DOWN = "MOUSE_LEFT_BUTTON_DOWN"
    MOUSE_LEFT_BUTTON_UP = "MOUSE_LEFT_BUTTON_UP"
    MOUSE_RIGHT_BUTTON_DOWN = "MOUSE_RIGHT_BUTTON_DOWN"
    MOUSE_RIGHT_BUTTON_UP = "MOUSE_RIGHT_BUTTON_UP"
