from __future__ import annotations

from collections.abc import Awaitable
from typing import Any, Protocol

from aetherion import EntityInterface, World
from aetherion.world.models import AIMetadataResponse


class WebSocketServerProtocol(Protocol):
    async def start(self) -> None: ...


class WorldInterfaceProtocol(Protocol):
    world: World
    last_state_response: bytes | None

    def walk_left_entity(self, entity_interface: EntityInterface) -> Any: ...
    def walk_up_entity(self, entity_interface: EntityInterface) -> Any: ...
    def walk_right_entity(self, entity_interface: EntityInterface) -> Any: ...
    def walk_down_entity(self, entity_interface: EntityInterface) -> Any: ...
    def jump_entity(self, entity_interface: EntityInterface) -> Any: ...
    def make_entity_eat(self, entity_interface: EntityInterface) -> Any: ...

    def get_ai_metadata(self) -> AIMetadataResponse | None: ...
    def set_entity_action_map(self, entity_action_map: dict[int, object], statistics: dict[str, float]) -> Any: ...
    def process_nn_actions(self) -> Any: ...

    def register_connected_entity(self, entity_id: int, name: str | None = None) -> Any: ...
    def register_list_of_connected_entities(self, entity_ids: list[int]) -> Any: ...
    def unregister_connected_entity(self, entity_id: int) -> Any: ...

    def get_perception_responses_async(
        self,
        entities_ids_with_queries: Any,
        entities_ids_connection_names: Any,
    ) -> Awaitable[bytes | None]: ...

